- name: Demo on finding files 
  hosts: nodes
  become: yes
  tasks:
    - find: 
        paths: /opt/apache-tomcat-9.0.10/webapps
        file_type: any
      register: out
    - file:
        path: "{{item.path}}"
        state: absent
      with_items: "{{out.files}}"  